export const AUTH_ACTIONS = {
    VERIFY_EMAIL: "SET_EMAIL_VERIFIED",
    SET_USER: "SET_CURRENT_USER",
    UPDATE_USER: "UPDATE_CURRENT_USER",
    COMPLETE_PROFILE: "COMPLETE_PROFILE",
    LOGOUT: "LOGOUT",
    REFRESH: "REFRESH"
}